/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Alberto Jimenez
 */
public class MenuRepartidor extends javax.swing.JFrame {

    /**
     * Creates new form MenuRepartidor
     */
    public MenuRepartidor() {
        initComponents();
        btnHistorialEntregas.setVisible(false);
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(0x22EEE5));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSeleccionarPedido = new javax.swing.JButton();
        btnHistorialEntregas = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("French Script MT", 3, 72)); // NOI18N
        jLabel1.setText("Kiawa Systems");

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 3, 24)); // NOI18N
        jLabel2.setText("REPARTIDOR");

        btnSeleccionarPedido.setBackground(new java.awt.Color(153, 255, 153));
        btnSeleccionarPedido.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnSeleccionarPedido.setText("Seleccionar Pedido");
        btnSeleccionarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarPedidoActionPerformed(evt);
            }
        });

        btnHistorialEntregas.setBackground(new java.awt.Color(153, 204, 255));
        btnHistorialEntregas.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnHistorialEntregas.setText("Historial Entregas");
        btnHistorialEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialEntregasActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(255, 153, 153));
        btnCerrarSesion.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCerrarSesion)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeleccionarPedido)
                    .addComponent(btnHistorialEntregas, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHistorialEntregas)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarPedidoActionPerformed

    private void btnHistorialEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialEntregasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialEntregasActionPerformed

    public JButton getBtnCerrarSesion() {
        return btnCerrarSesion;
    }

    public void setBtnCerrarSesion(JButton btnCerrarSesion) {
        this.btnCerrarSesion = btnCerrarSesion;
    }

    public JButton getBtnHistorialEntregas() {
        return btnHistorialEntregas;
    }

    public void setBtnHistorialEntregas(JButton btnHistorialEntregas) {
        this.btnHistorialEntregas = btnHistorialEntregas;
    }

    public JButton getBtnSeleccionarPedido() {
        return btnSeleccionarPedido;
    }

    public void setBtnSeleccionarPedido(JButton btnSeleccionarPedido) {
        this.btnSeleccionarPedido = btnSeleccionarPedido;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnHistorialEntregas;
    private javax.swing.JButton btnSeleccionarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
