/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CasosDeUso.CU.DarDeAlta;

import CasosDeUso.CU.DarDeAlta.ControlAdministrador;
import CasosDeUso.CU.DarDeAlta.GestionarEmpleados;
import Subsistema.FSubsistema_Cocinero;
import Subsistema.FSubsistema_Repartidor;
import dto.CocineroDTO;
import dto.RepartidorDTO;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author PC Gamer
 */

public class EditarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form DarDeAltaEmpleado
     */
    public EditarEmpleado() {
        initComponents();
        cmbDisponible.setVisible(false);
        txtRol.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }
    
    
        /** Llama a este método tras crear la ventana para rellenar los campos */
    public void acomodarCampos() {
        Object sel = ControlAdministrador.getInstancia().getEmpleadoSeleccionado();
        if (sel instanceof RepartidorDTO) {
            RepartidorDTO dto = (RepartidorDTO) sel;
            lblId.setText(dto.getIdRepartidor());
            txtNombre.setText(dto.getNombreCompleto());
            lblCurp.setText(dto.getCurp());
            txtSalarioDiario.setText(dto.getSalarioDiario()+"");
            txtTelefono.setText(dto.getTelefono());
            txtApodo.setText(dto.getApodo());
            txtDomicilio.setText(dto.getDomicilio());
            txtHorario.setText(dto.getHorario());
            txtDiasDeTrabajo.setText(dto.getDiasTrabajo());
            txtConsideracionesExtras.setText(dto.getConsideracionesExtras());
            cmbDisponible.setSelectedItem(dto.getDisponible());
        } else if (sel instanceof CocineroDTO) {
            CocineroDTO dto = (CocineroDTO) sel;
            lblId.setText(dto.getIdCocinero());
            txtNombre.setText(dto.getNombreCompleto());
            lblCurp.setText(dto.getCurp());
            txtSalarioDiario.setText(dto.getSalarioDiario()+"");
            txtTelefono.setText(dto.getTelefono());
            txtApodo.setText(dto.getApodo());
            txtDomicilio.setText(dto.getDomicilio());
            txtHorario.setText(dto.getHorario());
            txtDiasDeTrabajo.setText(dto.getDiasTrabajo());
            txtConsideracionesExtras.setText(dto.getConsideracionesExtras());
            cmbDisponible.setSelectedItem(dto.getDisponible());
        }
    }

    public JButton getBtnModificarEmpleado() {
        return btnModificarEmpleado;
    }

    public void setBtnModificarEmpleado(JButton btnModificarEmpleado) {
        this.btnModificarEmpleado = btnModificarEmpleado;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtApodo = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        txtSalarioDiario = new javax.swing.JTextField();
        txtDiasDeTrabajo = new javax.swing.JTextField();
        txtHorario = new javax.swing.JTextField();
        txtConsideracionesExtras = new javax.swing.JTextField();
        btnModificarEmpleado = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        txtRol = new javax.swing.JTextField();
        cmbDisponible = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblCurp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setText("   MODIFICAR A UN EMPLEADO");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Nombre Completo");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("Telefono");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setText("Domicilio");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setText("Apodo");

        txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setText("Salario Diario");

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setText("Dias de trabajo");

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel8.setText("Horario");

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setText("Consideraciones Extras");

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setText("Disponible");

        txtApodo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtDomicilio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtDiasDeTrabajo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtHorario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtConsideracionesExtras.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtConsideracionesExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsideracionesExtrasActionPerformed(evt);
            }
        });

        btnModificarEmpleado.setBackground(new java.awt.Color(153, 255, 153));
        btnModificarEmpleado.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        btnModificarEmpleado.setText("Crear Empleado");
        btnModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEmpleadoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setText("Rol:");

        btnRegresar.setBackground(new java.awt.Color(255, 102, 102));
        btnRegresar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Goudy Stout", 0, 12)); // NOI18N
        jLabel12.setText("Contraseña");

        txtRol.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cmbDisponible.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbDisponible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));
        cmbDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDisponibleActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("ID:");

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblId.setText("----");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Curp:");

        lblCurp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCurp.setText("----");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnRegresar)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblId)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModificarEmpleado)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(112, 112, 112))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtHorario)
                                    .addComponent(txtNombre)
                                    .addComponent(txtSalarioDiario)
                                    .addComponent(cmbDisponible, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(txtDiasDeTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(txtApodo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblCurp))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(txtConsideracionesExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel10))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblId)
                            .addComponent(jLabel14)
                            .addComponent(lblCurp))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalarioDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiasDeTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsideracionesExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnModificarEmpleado))
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEmpleadoActionPerformed

        String nombre = txtNombre.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String domicilio = txtDomicilio.getText().trim();
        String apodo = txtApodo.getText().trim();
        String salarioStr = txtSalarioDiario.getText().trim();
        String dias = txtDiasDeTrabajo.getText().trim();
        String horario = txtHorario.getText().trim();
        String extras = txtConsideracionesExtras.getText().trim();
        String curp = lblCurp.getText().trim();
        String contrasena = new String(txtContrasena.getPassword()).trim();
        
        if (contrasena == "") {
            
        }

        if (nombre.isBlank() || telefono.isBlank() || domicilio.isBlank() || apodo.isBlank()
                || salarioStr.isBlank() || dias.isBlank() || horario.isBlank() || curp.isBlank()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos obligatorios.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double salario;
        try {
            salario = Double.parseDouble(salarioStr);
            if (salario <= 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El salario debe ser un número válido y mayor a 0.", "Salario inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Object obj = ControlAdministrador.getInstancia().getEmpleadoSeleccionado();

        try {
            if (obj instanceof RepartidorDTO dto) {
                dto.setNombreCompleto(nombre);
                dto.setTelefono(telefono);
                dto.setDomicilio(domicilio);
                dto.setApodo(apodo);
                dto.setSalarioDiario(salario);
                dto.setDiasTrabajo(dias);
                dto.setHorario(horario);
                dto.setConsideracionesExtras(extras);
                dto.setCurp(curp);
              

                FSubsistema_Repartidor subs = new FSubsistema_Repartidor();
                subs.actualizarRepartidor(dto, contrasena); 
            } else if (obj instanceof CocineroDTO dto) {
                dto.setNombreCompleto(nombre);
                dto.setTelefono(telefono);
                dto.setDomicilio(domicilio);
                dto.setApodo(apodo);
                dto.setSalarioDiario(salario);
                dto.setDiasTrabajo(dias);
                dto.setHorario(horario);
                dto.setConsideracionesExtras(extras);
                dto.setCurp(curp);

                FSubsistema_Cocinero subs = new FSubsistema_Cocinero();
                subs.actualizarCocinero(dto, contrasena);
            }

            JOptionPane.showMessageDialog(this, "Empleado modificado correctamente.");
        this.dispose();
     //   ControlAdministrador.getInstancia().regresar();
            
            new GestionarEmpleados().setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al modificar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        txtApodo.setText("");
        txtConsideracionesExtras.setText("");
        txtContrasena.setText("");
        lblCurp.setText("");
        txtDiasDeTrabajo.setText("");
        txtDomicilio.setText("");
        txtHorario.setText("");
        txtNombre.setText("");
        txtSalarioDiario.setText("");
        txtTelefono.setText("");
    


    }//GEN-LAST:event_btnModificarEmpleadoActionPerformed

    private void txtConsideracionesExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsideracionesExtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsideracionesExtrasActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
      this.dispose();
        ControlAdministrador.getInstancia().regresar();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cmbDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDisponibleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarEmpleado;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbDisponible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCurp;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtApodo;
    private javax.swing.JTextField txtConsideracionesExtras;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtDiasDeTrabajo;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRol;
    private javax.swing.JTextField txtSalarioDiario;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
