/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CasosDeUso.CU.EntregarPedido;

import Control.ControlRepartidor;
import dto.PedidoDTO;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Alberto Jimenez
 */
public class ConfirmarEntrega extends javax.swing.JFrame {
    
    private double totalPedido;
    /**
     * Creates new form ConfirmarEntrega
     */
    public ConfirmarEntrega() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(0x22EEE5));
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnConfirmarPago = new javax.swing.JButton();
        btnNegarPago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirmar Pago");

        txtTotal.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Total a Pagar = $");
        jLabel8.setPreferredSize(new java.awt.Dimension(42, 16));

        btnConfirmarPago.setBackground(new java.awt.Color(153, 255, 153));
        btnConfirmarPago.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnConfirmarPago.setText("Confirmar Pago");

        btnNegarPago.setBackground(new java.awt.Color(255, 102, 102));
        btnNegarPago.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnNegarPago.setText("Negar Pago");
        btnNegarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal)))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnConfirmarPago))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnNegarPago)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnConfirmarPago)
                .addGap(18, 18, 18)
                .addComponent(btnNegarPago)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNegarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegarPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNegarPagoActionPerformed

    public void setDatosPedido(double totalPedido) {
        this.totalPedido = totalPedido;
    }
    
    private void cargarDatos() {
        PedidoDTO pedido = ControlRepartidor.getInstancia().getPedidoSeleccionado();

        if (pedido != null) {
            txtTotal.setText(String.format("%.2f", pedido.getTotal()));
        }
    }

    public JButton getBtnConfirmarPago() {
        return btnConfirmarPago;
    }

    public void setBtnConfirmarPago(JButton btnConfirmarPago) {
        this.btnConfirmarPago = btnConfirmarPago;
    }

    public JButton getBtnNegarPago() {
        return btnNegarPago;
    }

    public void setBtnNegarPago(JButton btnNegarPago) {
        this.btnNegarPago = btnNegarPago;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarPago;
    private javax.swing.JButton btnNegarPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
