/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CasosDeUso.CU.Equipo;

import Buscadores.BuscadorPlatillos;
import control.ControlPresentacion;
import dto.DetallePedidoDTO;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rayoa
 */
public class SeleccionarPlatillos extends javax.swing.JFrame {

    BuscadorPlatillos buscadorPlatillos = new BuscadorPlatillos();

    /**
     * Creates new form SeleccionarPlatillos
     */
    public SeleccionarPlatillos() {
        initComponents();
        this.pnlBuscadorPlatillos.add(buscadorPlatillos);
        this.buscadorPlatillos.getCmbDisponible().setVisible(false);
        this.buscadorPlatillos.getLblDisponible().setVisible(false);
        this.buscadorPlatillos.setVisible(true);
        this.setLocationRelativeTo(null);
        buscadorPlatillos.setOnPlatilloAgregado(() -> actualizarTablaSeleccionados());
        getContentPane().setBackground(new Color(0xffff90));
        
        buscadorPlatillos.setOnPlatilloDoubleClick(dto -> {
            String input = JOptionPane.showInputDialog(this, "¿Cuántas unidades deseas?");
            if (input == null) return;
            try {
                int cantidad = Integer.parseInt(input);
                if (cantidad < 1 || cantidad > dto.getExistencias()) {
                    JOptionPane.showMessageDialog(this, "Cantidad no válida.");
                    return;
                }
                DetallePedidoDTO det = new DetallePedidoDTO(
                    dto.getNombre(), cantidad, dto.getPrecio(),
                    "", dto.getPrecio() * cantidad
                );
                ControlPresentacion.getInstancia().agregarDetalle(det);
                JOptionPane.showMessageDialog(this, "Platillo agregado.");
                actualizarTablaSeleccionados();
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Ingresa un número válido.");
            }
        });
    

    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        if (b) {
            actualizarTablaSeleccionados();
        }
    }

    public void actualizarTablaSeleccionados() {
        DefaultTableModel modelo = (DefaultTableModel) tblPlatillosHastaElMomento.getModel();
        modelo.setRowCount(0);

        double total = 0.0;

        for (DetallePedidoDTO d : control.ControlPresentacion.getInstancia().getDetallesSeleccionados()) {
            modelo.addRow(new Object[]{
                d.getNombrePlatillo(),
                d.getCantidad(),
                d.getPrecioUnitario(),
                d.getNota(),
                d.getSubtotal()
            });
            total += d.getSubtotal();
        }

        lblTotal.setText(String.format("$ %.2f", total));
        ControlPresentacion.getInstancia().setTotal(total);
    }

    public JButton getBtnContinuar() {
        return btnContinuar;
    }

    public void setBtnContinuar(JButton btnContinuar) {
        this.btnContinuar = btnContinuar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBuscadorPlatillos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlatillosHastaElMomento = new javax.swing.JTable();
        btnEliminarPlatillo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        btnEditarNota = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1247, 778));

        pnlBuscadorPlatillos.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Carrito de Compras");

        tblPlatillosHastaElMomento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad", "Precio", "Nota", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPlatillosHastaElMomento);
        if (tblPlatillosHastaElMomento.getColumnModel().getColumnCount() > 0) {
            tblPlatillosHastaElMomento.getColumnModel().getColumn(0).setMinWidth(120);
            tblPlatillosHastaElMomento.getColumnModel().getColumn(0).setPreferredWidth(110);
            tblPlatillosHastaElMomento.getColumnModel().getColumn(0).setMaxWidth(120);
            tblPlatillosHastaElMomento.getColumnModel().getColumn(1).setMinWidth(80);
            tblPlatillosHastaElMomento.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblPlatillosHastaElMomento.getColumnModel().getColumn(1).setMaxWidth(80);
            tblPlatillosHastaElMomento.getColumnModel().getColumn(2).setMinWidth(100);
            tblPlatillosHastaElMomento.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblPlatillosHastaElMomento.getColumnModel().getColumn(2).setMaxWidth(100);
            tblPlatillosHastaElMomento.getColumnModel().getColumn(3).setMinWidth(150);
            tblPlatillosHastaElMomento.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblPlatillosHastaElMomento.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        btnEliminarPlatillo.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminarPlatillo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnEliminarPlatillo.setText("Eliminar Platillo");
        btnEliminarPlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPlatilloActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setText("Seleccionar Platillos");

        jLabel3.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel3.setText("Doble Click para Seleccionar Platillos");

        btnContinuar.setBackground(new java.awt.Color(153, 255, 153));
        btnContinuar.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnEditarNota.setBackground(new java.awt.Color(204, 204, 204));
        btnEditarNota.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnEditarNota.setText("Editar Nota");
        btnEditarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarNotaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Total:");

        lblTotal.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblTotal.setText("---");

        btnRegresar.setBackground(new java.awt.Color(255, 102, 102));
        btnRegresar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlBuscadorPlatillos, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 35, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEliminarPlatillo)
                                        .addGap(60, 60, 60))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEditarNota)
                                        .addGap(48, 48, 48))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(pnlBuscadorPlatillos, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnEditarNota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminarPlatillo)
                            .addComponent(jLabel4)
                            .addComponent(lblTotal))))
                .addGap(46, 46, 46)
                .addComponent(btnContinuar)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarPlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPlatilloActionPerformed
        int filaSeleccionada = tblPlatillosHastaElMomento.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un platillo para eliminar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar este platillo del carrito?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            control.ControlPresentacion.getInstancia().getDetallesSeleccionados().remove(filaSeleccionada);

            DefaultTableModel modelo = (DefaultTableModel) tblPlatillosHastaElMomento.getModel();
            modelo.removeRow(filaSeleccionada);
            JOptionPane.showMessageDialog(this, "Platillo Eliminado.", "Exito", JOptionPane.INFORMATION_MESSAGE);

            actualizarTablaSeleccionados();
        }
    }//GEN-LAST:event_btnEliminarPlatilloActionPerformed

    private void btnEditarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarNotaActionPerformed
        int filaSeleccionada = tblPlatillosHastaElMomento.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un platillo de la tabla.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String notaActual = (String) tblPlatillosHastaElMomento.getValueAt(filaSeleccionada, 3);
        String nuevaNota = JOptionPane.showInputDialog(this, "Introduce Nota:", notaActual);

        if (nuevaNota != null) {
            tblPlatillosHastaElMomento.setValueAt(nuevaNota, filaSeleccionada, 3);

            DetallePedidoDTO detalle = control.ControlPresentacion.getInstancia().getDetallesSeleccionados().get(filaSeleccionada);
            detalle.setNota(nuevaNota);
        }
    }//GEN-LAST:event_btnEditarNotaActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed


    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public void setBtnRegresar(JButton btnRegresar) {
        this.btnRegresar = btnRegresar;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnEditarNota;
    private javax.swing.JButton btnEliminarPlatillo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlBuscadorPlatillos;
    private javax.swing.JTable tblPlatillosHastaElMomento;
    // End of variables declaration//GEN-END:variables
}
