/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dto.UbicacionDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author
 * Ariel Eduardo Borbón Izaguirre    252116 
 * Freddy Ali Castro Román           252191 
 * Jesús Adrián Luzanilla Tapia      252699
 * Alberto Jiménez García            252595 
 * 
 */
public class SeleccionarUbicacion extends javax.swing.JFrame {

    private final ControlOrdenarPlatillo controlOrdenarPlatillo;
    private UbicacionDTO UbicacionSeleccionada;
    private List<UbicacionDTO> listaUbicaciones;
    
    /**
     * Creates new form SeleccionarUbicacion
     */
    public SeleccionarUbicacion(ControlOrdenarPlatillo controlOrdenarPlatillo) {
        initComponents();
        this.controlOrdenarPlatillo=controlOrdenarPlatillo;
        this.UbicacionSeleccionada = new UbicacionDTO();
        this.listaUbicaciones = this.controlOrdenarPlatillo.consultarUbicaciones();
        this.lblUsuario.setText("Bienvenid@ " + controlOrdenarPlatillo.obtenerAlumnoActual().getNombre());
        this.llenarTablaUbicaciones();
        this.seleccionarUbicacion();
        this.btnSeleccionarUbicacion.addActionListener(e->this.guardarUbicacion());
    }

    /*Se utiliza para obtener la ubicacion y poder usarla en otros form a traves de control*/
    public UbicacionDTO getUbicacionSeleccionada() {
        return UbicacionSeleccionada;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUbicacion = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUbicaciones = new javax.swing.JTable();
        btnSeleccionarUbicacion = new javax.swing.JButton();
        btnRegresarUbicacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInstrucciones = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUbicacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUbicacion.setText("Seleccionar Ubicacion");

        tblUbicaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Edificio", "Aula"
            }
        ));
        tblUbicaciones.setToolTipText("");
        tblUbicaciones.setAutoscrolls(false);
        jScrollPane1.setViewportView(tblUbicaciones);

        btnSeleccionarUbicacion.setText("Siguiente");
        btnSeleccionarUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarUbicacionActionPerformed(evt);
            }
        });

        btnRegresarUbicacion.setText("Regresar");
        btnRegresarUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarUbicacionActionPerformed(evt);
            }
        });

        jLabel1.setText("Instrucciones de entrega");

        txtInstrucciones.setColumns(20);
        txtInstrucciones.setRows(5);
        jScrollPane2.setViewportView(txtInstrucciones);

        jLabel2.setText("Telefono");

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegresarUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSeleccionarUbicacion))
                    .addGroup(panelTablaLayout.createSequentialGroup()
                        .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionarUbicacion)
                    .addComponent(btnRegresarUbicacion))
                .addContainerGap())
        );

        lblUsuario.setText("Bienvenido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblUsuario)
                .addGap(103, 103, 103)
                .addComponent(lblUbicacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUbicacion)
                    .addComponent(lblUsuario))
                .addGap(64, 64, 64)
                .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarUbicacionActionPerformed
        // TODO add your handling code here:
        if (UbicacionSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "No has seleccionado ninguna ubicacion.", "Error", JOptionPane.WARNING_MESSAGE);
        }else if(this.txtTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No has proporcionado un numero de telefono.", "Error", JOptionPane.WARNING_MESSAGE);
            
        }else if (!this.txtTelefono.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "El número de teléfono solo debe contener números.", "Error", JOptionPane.WARNING_MESSAGE);
            
        }else if (this.txtTelefono.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "El número de teléfono debe tener 10 dígitos.", "Error", JOptionPane.WARNING_MESSAGE);
                            
        }else{
            controlOrdenarPlatillo.iniciarFrmConfirmarPedido();
            dispose();
        }
        
    }//GEN-LAST:event_btnSeleccionarUbicacionActionPerformed

    private void btnRegresarUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarUbicacionActionPerformed
        // TODO add your handling code here:
        controlOrdenarPlatillo.iniciarCasoUsoPedido();
        dispose();
    }//GEN-LAST:event_btnRegresarUbicacionActionPerformed
    
    /*Llenado de la tabla*/
    private void llenarTablaUbicaciones(){
        DefaultTableModel modelo = (DefaultTableModel)this.tblUbicaciones.getModel();
        modelo.setRowCount(0);
        for(UbicacionDTO ubicacion : this.listaUbicaciones){
            Object[] filaTabla = {
                ubicacion.getEdificio(),
                ubicacion.getAula(),
            };
            modelo.addRow(filaTabla);
        }
    }
    
    
    /*Este metodo guarda la informacion de la fila seleccionada y los datos de los campos de instrucciones y telefono*/
    private void guardarUbicacion(){
        
        int filaSeleccionada = this.tblUbicaciones.getSelectedRow();
        if (filaSeleccionada!=-1 && !this.txtTelefono.getText().isEmpty()) {
            /*Se recuperan los varoles del campo de la tabla seleccionada*/
            String edificio = this.tblUbicaciones.getValueAt(filaSeleccionada, 0).toString();
            String aula = this.tblUbicaciones.getValueAt(filaSeleccionada, 1).toString();
            /*Se recuperan los varoles de los campos de texto*/
            String telefono = this.txtTelefono.getText();
            String instrucciones = this.txtInstrucciones.getText();

            /*Se añade a la lista la ubicacion seleccionada*/
            this.UbicacionSeleccionada = new UbicacionDTO(edificio,aula,telefono,instrucciones);

            /*Se muestra la ubicacion en consola era para pruebas*/
            System.out.println("Ubicacion e instrucciones seleccionadas:");

            
            System.out.println(UbicacionSeleccionada.getEdificio() + " " + UbicacionSeleccionada.getAula() + " " + UbicacionSeleccionada.getTelefono() + " " + UbicacionSeleccionada.getInstruccionesEntrega());
            
        }
    }
    
    /*Este metodo solo selecciona una fila de la tabla pero no guarda nada*/
    private void seleccionarUbicacion(){
        this.tblUbicaciones.getSelectionModel().addListSelectionListener(e->{
            if (!e.getValueIsAdjusting()) {
                int filaSeleccionada = this.tblUbicaciones.getSelectedRow();
                if (filaSeleccionada!=-1) {
                    System.out.println("fila seleccionada: "+ filaSeleccionada);
                    
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresarUbicacion;
    private javax.swing.JButton btnSeleccionarUbicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTable tblUbicaciones;
    private javax.swing.JTextArea txtInstrucciones;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
