/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CasosDeUso.CU.TomarPedido;

import Control.ControlPedido;
import dto.PedidoDTO;
import dto.RepartidorDTO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author jalt2
 */
public class AsignarPedido extends javax.swing.JFrame {
    
    private ControlPedido control;
    private PedidoDTO pedidoSeleccionado;
    
    /**
     * Creates new form AsignarPedido
     */
    public AsignarPedido() {
        initComponents();
        control = ControlPedido.getInstance();
        pedidoSeleccionado = control.recuperarPedidoSeleccionado();
        llenarComboBoxRepartidores();
        this.txtPedidoSeleccionado.setText(pedidoSeleccionado.getIdPedido());
    }
    
    private void llenarComboBoxRepartidores(){
        List<RepartidorDTO> listaRepartidores = control.recuperarRepartidoresDisponibles();
        
        for(RepartidorDTO r : listaRepartidores){
            this.cmbRepartidores.addItem(r.getNombreCompleto());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPedidoSeleccionado = new javax.swing.JTextField();
        cmbRepartidores = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnAsignarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pedido Seleccionado");

        jLabel2.setText("Repartidores ");

        btnAsignarPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAsignarPedido.setText("Asignar Pedido");
        btnAsignarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPedidoSeleccionado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRepartidores, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAsignarPedido)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPedidoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRepartidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(btnAsignarPedido)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarPedidoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "El pedido fue asignado a "+cmbRepartidores.getSelectedItem().toString(), "Pedido asignado", JOptionPane.INFORMATION_MESSAGE);
        control.asignarPedidoRepartidor(pedidoSeleccionado.getFolio(), pedidoSeleccionado.getNombreRepartidor());
    }//GEN-LAST:event_btnAsignarPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarPedido;
    private javax.swing.JComboBox<String> cmbRepartidores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtPedidoSeleccionado;
    // End of variables declaration//GEN-END:variables
}
