/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CasosDeUso.CU.TomarPedido;

import Control.ControlPedido;
import Subsistema.FSubsistema_Pedidos;
import dto.PedidoDTO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jalt2
 */
public class PedidosAsignar extends javax.swing.JFrame {
    
    private PedidoDTO pedidoSeleccionado;
    private ControlPedido control;
    /**
     * Creates new form PedidosRepartidor
     */
    public PedidosAsignar() {
        initComponents();
        llenarTabla();
        control = ControlPedido.getInstance();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidosAsignar = new javax.swing.JTable();
        btnSeleccionarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPedidosAsignar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pedido", "Estado", "Fecha y Hora", "Repartidor"
            }
        ));
        jScrollPane1.setViewportView(tblPedidosAsignar);

        btnSeleccionarPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSeleccionarPedido.setText("Seleccionar Pedido");
        btnSeleccionarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSeleccionarPedido)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnSeleccionarPedido)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarPedidoActionPerformed
        try {
            // TODO add your handling code here:
            seleccionarPedido();
            control.iniciarFrmAsignarPedido();
        } catch (ParseException ex) {
            Logger.getLogger(PedidosAsignar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSeleccionarPedidoActionPerformed
    
    private void llenarTabla(){
        try {
            DefaultTableModel modelo = (DefaultTableModel) tblPedidosAsignar.getModel();
            modelo.setRowCount(0);
            
            FSubsistema_Pedidos fSubsistema_pedidos = new FSubsistema_Pedidos();
            
            List<PedidoDTO> listaPedidos = new ArrayList<>();
            listaPedidos = fSubsistema_pedidos.recuperarPedidos();
                    
            for (PedidoDTO pedido : listaPedidos) {
                modelo.addRow(new Object[]{
                    pedido.getIdPedido(),
                    pedido.getEstado(),
                    pedido.getFechaPedido().toString(),
                    pedido.getNombreRepartidor()
                });
            }
            
            
        } catch (Exception ex) {
            Logger.getLogger(PedidosAsignar.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    private void seleccionarPedido() throws ParseException{
        int filaSeleccionada = tblPedidosAsignar.getSelectedRow();
        
        if (filaSeleccionada >= 0) {
            String idPedido = tblPedidosAsignar.getValueAt(filaSeleccionada, 0).toString();
            String estado = tblPedidosAsignar.getValueAt(filaSeleccionada, 1).toString();
            String fecha = tblPedidosAsignar.getValueAt(filaSeleccionada, 2).toString();
            String repartidor = tblPedidosAsignar.getValueAt(filaSeleccionada, 3).toString();
            
            SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
            Date fechaFormateada = formato.parse(fecha);
            
            pedidoSeleccionado = new PedidoDTO(idPedido, fechaFormateada, estado, repartidor);
            
        }
    }

    public PedidoDTO guardarPedidoSeleccionado(){
        return pedidoSeleccionado;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionarPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPedidosAsignar;
    // End of variables declaration//GEN-END:variables
}
